### ISSUE TITLE
No GroundStations when using Kopernikus in 1.8 (without RSS mod)

### ISSUE THREAD

**Issue by bofhgr** [DRVeyl/RealAntennas#20]
Hi! Amazing mod! thanks!! 
I have been waiting for an 1.8 release (using the pre-release version atm) along with Kopernikus for 1.8. All installed via CKAN. I don't have RSS and I see you have a RealAntennas config for RSS when using Kopernikus, but is there a Real Antennas config for when using Kopernikus with the stock solar system? Currently when I use it with the Stock solar system *aka just intall Kopernikus mod for the EVA footprints, I don't seem to have any Ground Stations on Kerbin.

**Comment by DRVeyl** [comment]
Huh, I hadn't considered the use case for having Kopernicus but no planet pack.  As an interim fix for this, you can change lines 232 and 276 of RealAntennasCommNetParams.cfg in Gamedata\RealAntennas from  Kopernicus:NEEDS[!Kopernicus] to  just   @Kopernicus

Both would need the @ in front, since Kopernicus itself will define the structure.

Short of creating a stock config entry on CKAN (similar to RealPlume's approach), I could add a stock.cfg.disabled file into Gamedata and add a note to the wiki to enable that in cases like yours.  I think that's the simplest fix for now.

**Comment by bofhgr** [comment]
yup sounds simple enough, thank you and keep up the awesome work! 

As a follow-up, I tend to disable the other 2 ground stations by commenting out lines 251-270 in that .cfg to give myself an excuse to build a comm network. With this workaround, if I understand it correctly, I'd have to comment out lines 318-332 for the same effect, yes?

Also, instead of the .disabled file workaround option, and without changing what you already have for stock compatibility, couldn't you tell MM to send the config to Kopernicus if it finds it installed, but not if it finds RSS/RO in which case it will run that part during the RSS initialization. Not sure if I relay this correctly, not very familiar with how KSP mods interact with MM just yet. like @Kopernicus:NEEDS[!RSS]

**Comment by DRVeyl** [comment]
Yes, you can add or remove ground stations in this config or later in a stock config when I make that.  I don't currently make any claims about stock "balance" with the existing ground stations.  They might be too powerful, or because of the scale of the stock system you might be able to do just fine with only actual antenna parts.

What you suggest would work, except then I would need to account for any other planet pack and add that to the exclude list like in your example.  There isn't a great general approach.  Having a planet pack means having Kopernicus, but apparently having Kopernicus does not mean having a planet pack ;)

**Comment by bofhgr** [comment]
hm the workaround doesn't seem to work for me, I guess it needs more messing around with the @ definitions for the cities and whatnot, tbh I simply removed Kopernicus for now, the 1.8.1 version works very well without it (had it for the EVA footprints but meh), will probably re-add it when I switch to RSS anyways. Thanks for your time!
PS: have to give you a kudos for the performance of this mod, compared to a similar RT setup this feels so smooth! only missing the delay functionality that made it cool, but rather prefer your approach to how signal/bitrates work in space better than the delay mechanic in ksp. keep up the good work!

**Comment by DRVeyl** [comment]
Believe this is fixed in https://github.com/DRVeyl/RealAntennas/commit/52b509ee6e47b2c65f7ffb9f0e958ffe6b94e193 and available in the latest 1.8 Pre-Release updated today.

**Comment by DRVeyl** [comment]
Fixed and formally released in https://github.com/DRVeyl/RealAntennas/releases/tag/v1.1

**Comment by Omni-MC** [comment]
This seems to be an issue again. 

Installed Mods:
 
Kopernicus _release-1.8.1-1_
ModularFlightIntegrator _1.2.7.0_
Module Manager _4.1.3_
Real Antennas _v1.2_
