### ISSUE TITLE
SAS doesn't work when this mod is installed

### ISSUE THREAD

**Issue by oOBoomberOo** [DRVeyl/RealAntennas#29]
You can activate SAS mode but it won't do anything. This affected both manned and probe SAS.

**Comment by DRVeyl** [comment]
I don't understand.  RA doesn't directly touch anything regarding autopilot controls ie SAS [or what MJ does] -or- user input.  It relies on stock CommNet behaviour for those, such as the restrictions on partial control.

**Comment by oOBoomberOo** [comment]
No idea, I just found this by disabling other mods one-by-one until SAS start working again and found this.

**Comment by DRVeyl** [comment]
That does not give me anything to go on.  When you remove RA, do you still have CommNet on?  Are you familiar with the CommNet icons in the upper left, and the stock difficulty setting for partial versus full control?  Maybe provide a screenshot that shows what you're describing.

**Comment by oOBoomberOo** [comment]
Sure thing.

[Without Real Antennas](https://youtu.be/MQGOhsplE18)
[With Real Antennas](https://youtu.be/ePiuYuJuyvU)
The rocket is 100% stock and the setting should still be the same since I use the same save.

**Comment by DRVeyl** [comment]
One interesting thing is in the RA video you don't have a comms link, whereas in the stock video you do.  So there is something strange going on in the background.  Post KSP.log, please, of a run with RA installed.

**Comment by oOBoomberOo** [comment]
[KSP.log](https://github.com/DRVeyl/RealAntennas/files/4810851/KSP.log)

**Comment by DRVeyl** [comment]
Ok.  1.9.1.  In just a stock install of 1.9.1 with only RA, I do not see any of this behaviour.

BLUF: Try removing SignalDelay.

```
[LOG 05:01:31.235] [RACommNetNetwork] Rebuilding CommVessel on Ast. HSJ-227 (unloaded) (Vessel).  (Was Ast. HSJ-227 (unloaded) (SignalDelay.SignalDelayVesselModule) of type SignalDelay.SignalDelayVesselModule)
[LOG 05:01:31.236] [RACommNetNetwork] Rebuilding CommVessel on あっ。。。 (unloaded) (Vessel).  (Was あっ。。。 (unloaded) (SignalDelay.SignalDelayVesselModule) of type SignalDelay.SignalDelayVesselModule)
```
Unexpected, but I think this is tied in to the many Vessel.UpdateVesselModuleActivation errors -- maybe a weird interaction with SignalDelay and RA competing for the same kind of component.

```
[LOG 04:57:05.925] Config(@PART[IR_Adapter_0625ToTrussLarge]:FOR[RealismOverhaul]) MagicSmokeIndustries/RO/@PART[IR_Adapter_0625ToTrussLarge]:FOR[RealismOverhaul]
```
InfernalRobotics is causing some problems.  This is very bad practice for a patch, to use :FOR[AnotherMod].  Doing so basically declares to every other mod that AnotherMod, in this case RealismOverhaul, is installed in your game.  So RA detected that RO was installed because of that patch and gave you its RO configs.  This won't break RA but it will give you incorrect/unintended configuration in stock.  (Specifically, the UHF/VHF bands and the extremely low data rate at the very early game are not intended for RA in stock.)  Please open an issue in the InfernalRobotics GitHub regarding any patches using :FOR[AnotherMod].  They MUST use BEFORE or AFTER.

Your log is full of 
```
[EXC 05:01:35.319] NullReferenceException
	Vessel.UpdateVesselModuleActivation () (at <55ba45dc3a43403382024deac8dcd0be>:0)
	Vessel.Update () (at <55ba45dc3a43403382024deac8dcd0be>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
``` 
Even in the flight scene.  Based on stock UpdateVesselModuleActivation, you appear to have a null VesselModule.  See above about SignalDelay.  I assume these go away also if you just uninstall RA?

```
[ERR 05:01:58.605] Module ModuleRealAntenna threw during OnStart: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at RealAntennas.ModuleRealAntenna.ConfigBandOptions () [0x000b9] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
  at RealAntennas.ModuleRealAntenna.OnStart (PartModule+StartState state) [0x0017e] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
  at Part.ModulesOnStart () [0x00120] in <55ba45dc3a43403382024deac8dcd0be>:0 
``` 
That one is mine, and I'll look at how that came about.  I have a couple of guesses, based on:

You appear to have launched a craft straight out of the Spacecenter without opening it in the Editor.  I'm guessing a vessel that was created/saved without RA, because it still had a ModuleDataTransmitter on it, and it wouldn't if you had placed a new Mk1 pod.  I think you ended up just trying to launch a vessel that had never gotten any of its RA parts configured at all.  "Don't do that" but if that's the case I can detect it and give something valid instead of choking.

**Comment by oOBoomberOo** [comment]
I see, I'll try that.
