### ISSUE TITLE
Feature Request: Planning altitude manual number entry

### ISSUE THREAD

**Issue by thunder175** [DRVeyl/RealAntennas#36]
Could we please have the ability to enter a number manually on the planning altitude when we enable the # button on the PAW the same as the other RA entries? I often find the current scaling of the slider too high and would rather just type in a specific entry than try to mess around with dragging the slider.

**Comment by DRVeyl** [comment]
Would be great. Unfortunately, only a few different kinds of UI controls for the PAW support direct number entry. Isn't just a matter of turning it on. I really wish the scale edit did, because you're absolutely right that some ranges are very difficult to deal with using a slider. (The difference between "1" and "2" of any unit is very significant for planning.) Unfortunately, I believe the current modes allowing direct input would be completely useless in their traditional (slider) mode.

I very much wanted to avoid writing any custom hacks of PAW controls, but I might need to. The new scale edit is not being as user friendly as many would like.

**Comment by austinjames314** [comment]
What about multiple sliders (each at a different scale), and summing the values?

**Comment by DRVeyl** [comment]
IMO too messy.  That'd be a lot of sliders, since a single slider only has ~100 points for precision.  No, I'll probably need to actually put together something more custom.  You need to independently tune the exponent from the value.  So two sliders, one for the exponent (goes from 0 to 15 I guess), one for the value (goes from 0.0 to 9.9 in steps of 0.1).  Then a label to combine the two and tell you what you have.  Three rows, still pretty gross.

**Comment by austinjames314** [comment]
Yeah more than one slider is ugly from a UI perspective, but at least the group can be collapsed when not in use. So much of the time though, I want to check signal in the 1300 - 1700 km range though, and only having 1 or 2 Mm is frustrating. The value and exponent idea sounds like it'd work.

**Comment by DRVeyl** [comment]
Not implementing a custom UI control yet.  But I think this will meet the goals: https://github.com/DRVeyl/RealAntennas/commit/1dac75d5fcae2659779ba2a828ae7c49d62a7d5b
Still uses the existing UI_ScaleEdit.  Added more intervals that now only span 1 order of magnitude.  Planner defaults to 1Mm (in the range 1.0 - 10.0 Mm) instead of 10km.  Basically, it's now much easier to hit the difference between 1 and 2.  Exact precision isn't that useful, since everything is on a log scale.
