### ISSUE TITLE
Feature Request: Add relay flag to radio parts

### ISSUE THREAD

**Issue by thunder175** [DRVeyl/RealAntennas#60]
I propose adding an explicit relay true/false to the radio part config. This would force a part to have 'relay = true' in order to allow for crosslinking with other orbital assets. If 'relay = false', then that radio part can only communicate with a ground station in the case of a omnidirectional antenna, or specified vehicle target in the event of a dish.

**Comment by DRVeyl** [comment]
There was an early design decision that all antennas can relay, because the technology involved to do so is trivial.  The distinction of "this antenna is -allowed- to relay" is a KSPism that I didn't particularly have a desire to keep.

Eventually (as of v2.1, which isn't released as of this writing) I implemented this as a minimum tech level to be allowed to relay.  I don't think this has a point in the stock environment, and didn't have much of one in the RO environment either, *except* for a unique corner case in RP-1 career progression.  Very early tech levels (pre 1960s) set very low power consumption to correspond with the fact that the real-world equipment didn't include a receiver.  It couldn't just not relay, it was deaf.  But CommNet doesn't have a concept of 1-way-ness of links.  And an antenna that doesn't allow control is a weird thing that also doesn't play well with underlying KSP assumptions.  This would be fine, but it lead to a meta where long-term omni "relay" antennas went out at TL-1 because of the <1W power consumption, well after newer tech levels were unlocked, and because the limits on data rate didn't matter because the science experiment sizes are also vey low.

(For RO, the default min TL to relay is 2.  For stock, it is 0.)

**Comment by thunder175** [comment]
You definitely understand the inner working of the game much better than I ever will, so I will take your word for any creative design decisions. The main driver for my comment is that right now when on the same band, I have upper stage avionics cores relaying (allowing control) thru the detached payloads. Its not a huge deal since the upper stages batteries will wear out eventually.

If channelization became a thing with my other open issue then this becomes moot, since I would create a segregated TT&C link per band for avionics cores and leave mission payloads on another.

**Comment by DRVeyl** [comment]
Going to close this one, as IMO there are better alternatives if the problem as stated needs to be solved.
