### ISSUE TITLE
Guides update

### ISSUE THREAD

**Issue by nicesub** [DRVeyl/RealAntennas#65]
Hi,

Thank you for this awesome mod. So far I am still trying to figure out everything but its getting there. 
I am reading the guides that are available here and I feel that there are some gaps. For example what is Launch control panel and how to operate it? I see that there are some changes done to the map as well. Now I see some cones which are not there with stock game.
Then there is option to aim directional antennas at targets and I was wondering how does that work? Can omni speak directly to directional antenna? Then in the band guide you mention UHF and VHF but in my science mode game I have L band and up. So now I dont know what is L band. 
Apologies if answers to my questions are there in some guides already. I admit I am bad at navigating Github.

**Comment by DRVeyl** [comment]
There's a lot of useful info in the wiki, which you've found.  I'm not personally particularly good at providing that documentation, so it's a good thing it's on a wiki that can be edited by the players!  The planner guide was recently rewritten, as several GUIs changed going to the latest version.  But to your point, I don't think those questions are answered on the wiki... yet.

There's a lot of inspiration drawn from the mod RemoteTech.  But not being familiar with that, the similarities aren't helpful.  I'll put some answers here, in hopes they make their way onto the wiki.

Directional antennas display their viewing areas on the map in cones.  Two cones are drawn: the inner represents the -3dB point (where only half the power is present), and the outer represents the -10dB point, where only 1/10th of the power is present.  Beyond the outer cone, RealAntennas treats an antenna as completely deaf.  An antenna cannot talk to another antenna if it is outside of the outer cone.  Antennas work best when talking to other antennas that are in the middle of the cones.  The closer towards the edge, the more penalty it has.

A link can be created between any two antennas.  And currently, all antennas can relay.  (This is configurable, but in stock the minimum tech level for it is 0.)  Directional antennas can talk to other directional antennas or to omnis.

UHF and VHF exist only in the RealismOverhaul configs.  That's the majority of the users, so that's what they wrote about.  In stock, "L band" takes the place of UHF and VHF.

**Comment by nicesub** [comment]
Thank you DRVeyl
