### ISSUE TITLE
Near Future Exploration pack

### ISSUE THREAD

**Issue by nicesub** [DRVeyl/RealAntennas#66]
Hello,

Just a quick question. I am using Near Future Exploration pack which adds a bunch of antennas and parts. Most of the stuff from that pack I think works fine with this mod. Except:
1) The mod has antenna feeds and dishes that acts as reflectors. Basically the mod asks you to combine feed with dish to have it working to its potential. However, RA mod thinks that feed are omni antennas which I dont think they should be as they are feeds. Also some of the dish reflectors cannot be extended and the mod thinks they are antennas which in fact they are nothing until feed is pointed into them.
2) There are some antennas that come with NFE which are massive, Hence in VAB they are folded, however as soon as I place them on the vehicle in the VAB they auto deploy and the button to extend/retract is gone. Hence these beast are impossible to lift in orbit as flight through atmosphere would destroy them.

Are there any plans to make RA and NFE more compatible? I am kinda interested in that as I am using Outer Planets Mod which adds planets that are bit further away and having these additional antennas from NFE help with comms and huge science transfers.

**Comment by DRVeyl** [comment]
I've looked at it a couple times.  There isn't any plan to try to add compatibility with the feed+reflector system.
Some feeds are directional, but generally speaking they are just an element to excite, and so treating the part alone as an omni is generally correct -- a naked feed without a reflector is usually that.  If you can identify specific feeds that have directional properties (ie an LPA feed) then I can review and merge a PR.

For reflectors, yes, RA treats them as the directional antenna.  Because RA doesn't deal with multi-part... parts... there's no point to treating a reflector as not an antenna.  RA then makes a specific assumption regarding the reflector and feed: that all antennas are appropriately physically dimensioned so that the reflector size is neither significantly larger nor smaller than how the feed would illuminate it.

RA doesn't influence the deployable-ness of a part, though.  RA replaces `ModuleDataTransmitter` (the thing that makes it exist in CommNet and transmit science) but not `ModuleDeployablePart` (the thing that makes it retract/deploy).  This makes me confused about your issue #2, but I don't know what the RA patching would be doing to affect this.  What happens when you don't have RA?  Do these parts not have ModuleDeployablePart in their ConfigCache?

**Comment by nicesub** [comment]
Hi,

Thank you for detailed answer for no 1 question. As for no 2, I did a test this morning where I removed RA and then I tried the problematic parts again in VAB. Results are:

- Removing RA and trying the parts again seems to fix the issue, the dishes which before would autodeploy now do not do that and button to deploy them manually is back. Also the dishes which before did not have button to extend now have that button back again and can be extended.
- Reinstalling RA seems to introduce the issue again. Dishes that autodeploy and no button to retract them, also some of the dishes are stuck in retracted position cannot be extended as there is no button for that.

Let me know if you need some data or logs to help with finding out the root cause.

**Comment by DRVeyl** [comment]
Ok.  Which ones are not working?  I'm going to guess the 6 `nfex-antenna-reflector-*` patched here: <https://github.com/DRVeyl/RealAntennas/blob/master/GameData/RealAntennas/Parts/NFE_CAE_RTREDEV.cfg#L67-L105> and also line 175

When the patches were written, the `ModuleDeployableReflector` was removed.  Glancing at the source in NFX, I don't think that is necessary and it shouldn't impact anything with RA.  Try removing `	!MODULE[ModuleDeployableReflector] {}` from the patches in that file?

Most of the smarts from NFEX are in `ModuleAntennaFeed` which I would be more concerned with.  NFX itself detects RA [or RemoteTech] and removes the module, though.

**Comment by nicesub** [comment]
I made changes on my end as instructed and that did the trick. Now the dishes can be controlled when to extend and retracts as the button for that is back. I guess you can implement this change now in your next mod update?

**Comment by Grimmas** [comment]
Supporting NFE feeds and reflectors would've been a great addition to this mod, it's unfortunate that it's not on the table.
