### ISSUE TITLE
Kerbalism Support

### ISSUE THREAD

**Issue by edusaraiva** [DRVeyl/RealAntennas#79]
Hi I'm playing with kerbalism and PBC and I wanted to get a bit more complex with my communications.... ahhahahaha... there is anyway to make RA work properly with kerbalism?
As far as I noticed even though the interface from RA is working ok... looks like kerbalism is still been resposible for the kb/s for the connection...
Sorry If here is not the proper place to ask this.... didn't find this answer anywhere else
Just to be a bit more precise for example in my planning is showing that I would get 31 kbps but when I'm launching i'm getting 3.9 kbps

**Comment by DRVeyl** [comment]
RealAntennas has had integration with Kerbalism since just about the beginning.
The current dev build of Kerbalism, when the 4.0 comms code was backported to support RemoteTech, may have broken that.  But at least as of the latest published CKAN release, things are working well!

The issue you've identified is actually that Kerbalism is presenting in kBps (kiloBytes per second), whereas RA presents everything in [mega/kilo]BITS per second.  So they'll differ by exactly a factor of 8.

Check out either the RO or Kerbalism Discords.  Both have communities that are pretty responsive and helpful.
