### ISSUE TITLE
About the Modulation of DSN Tracking Station

### ISSUE THREAD

**Issue by SaberCF** [DRVeyl/RealAntennas#86]
I noticed that the modulation of DSN only has QPSK, not the higher modulation like 8PSK or even 64-QAM in the vessel's antenna.
Why DSN cannot use the higher modulation?

**Comment by DRVeyl** [comment]
Because, well, it doesn't.  <https://deepspace.jpl.nasa.gov/dsndocs/810-005/208/208B.pdf>
8PSK is a more likely adoption; amplitude modulation schemes aren't happiest when you're pushing them through a, or multiple, atmospheres.  I think you'll find it in use in the Near Earth Network, and commercial SATCOM.  At any rate, it is less efficient to increase modulation than to increase bandwidth.  Unless you have enough link margin to completely fill the link -- and you very likely don't when you're talking interplanetary distances and power management on probes -- there's minimal value in trading bandwidth for higher order modulation.

**Comment by SaberCF** [comment]
Thanks for the paper and reply! I haven't thought about atmosphere's influence to the DSN communication.
