### ISSUE TITLE
About RealismOverhaul.cfg

### ISSUE THREAD

**Issue by SaberCF** [DRVeyl/RealAntennas#87]
It says the encoder is Analog FSK in TL0, but I find that FSK is a digital modulation, so analog FSK should not exist, it should be FM( Frequency Modulation) for the analog signal. Is it right?

https://github.com/DRVeyl/RealAntennas/blob/5918116e583847003a62089e514b1e138e32095e/GameData/RealAntennas/RealismOverhaul.cfg#L84

**Comment by DRVeyl** [comment]
The entirety of RealAntennas is written using modern digital communications theory.  It doesn't handle some analog concepts very well, and doing so wasn't of interest to me.  The TL0 config you reference is a hack to support early RP-1 games that need pre-digital communication systems.  You get a bit of nonsense to force the very low data rates, rather than trying to track the widely varying frequency allocations used then.  Yes, they probably were FM.  I'm not writing rules for FM. :)
